"""Type stub for the C guardian extension."""

def activate(
    config: object,
    exc_class: type,
    token_id: int,
    snapshot: list[tuple[object, str, bool]],
) -> None: ...
def deactivate(token_id: int) -> None: ...
def is_active() -> bool: ...
def check_token(token_id: int) -> bool: ...
